version: "3.8"

services:
  app-server:
    image: dyogocae/store:0.0.2
    ports:
      - "8080:8080"
    restart: always

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

